function(check_required_vars)
	foreach(var ${ARGN})
		if(NOT DEFINED "${var}")
			message(FATAL_ERROR "required cmake variable not set: ${var}.\nRequired variables should be set in the Benchmarks main CMakeLists.txt")
		else()
			message(STATUS "${var}: ${${var}}")
		endif()
	endforeach()
endfunction()
