include(TryFindPackageCfg)
try_find_package_cfg()

if(ZLIB_FOUND)
	return()
endif()

if(MSVC OR MINGW)
	include(FindAnyStandardLib)
	if (WINCE)
		set(WINCE_PATH $ENV{NG_THIRDPARTY_ROOT}/wince)
		find_path(ZLIB_INCLUDE_DIRS zlib.h PATHS ${WINCE_PATH}/include CMAKE_FIND_ROOT_PATH_BOTH)
		#message(FATAL_ERROR ZLIB_INCLUDE_DIRS=${ZLIB_INCLUDE_DIRS})
		find_library (ZLIB_LIBRARIES zlib.lib PATHS ${WINCE_PATH}/lib CMAKE_FIND_ROOT_PATH_BOTH)
		#message(FATAL_ERROR ZLIB_LIBRARIES=${ZLIB_LIBRARIES})
		set(ZLIB_FOUND YES)
		find_any_standard_lib_coda(ZLIB)
	else()
		find_any_standard_lib(ZLIB $ENV{NG_THIRDPARTY_ROOT} zlib)
		find_any_standard_lib_coda(ZLIB)
	endif()
else()
	include(IncludeStandardFindModule)
	include_standard_find_module()
endif()
