include(TryFindPackageCfg)
try_find_package_cfg()

if(PNG_FOUND)
	return()
endif()

if(MSVC OR MINGW)
	include(FindAnyStandardLib)

	if (WIN32 AND CMAKE_COMPILER_IS_GNUCC)
		set(GNUWIN32_PATH $ENV{NG_THIRDPARTY_ROOT}/mingw)
		find_path(PNG_INCLUDE_DIR png.h HINTS ${GNUWIN32_PATH}/include)
		#message(FATAL_ERROR PNG_INCLUDE_DIR=${PNG_INCLUDE_DIR})
		set(PNG_INCLUDE_DIRS ${PNG_INCLUDE_DIR})
		find_library(PNG_LIBRARIES libpng.a HINTS ${GNUWIN32_PATH}/lib)
		#message(FATAL_ERROR PNG_LIBRARIES=${PNG_LIBRARIES})
		find_path(ZLIB_INCLUDE_DIRS zlib.h HINTS ${GNUWIN32_PATH}/include)
		#message(FATAL_ERROR ZLIB_INCLUDE_DIRS=${ZLIB_INCLUDE_DIRS})
		find_library (ZLIB_LIBRARIES libzlibstatic.a HINTS ${GNUWIN32_PATH}/lib)
		#message(FATAL_ERROR ZLIB_LIBRARIES=${ZLIB_LIBRARIES})
		list(APPEND PNG_LIBRARIES ${ZLIB_LIBRARIES})
		set(PNG_FOUND YES)
	elseif(WINCE)
		set(WINCE_PATH $ENV{NG_THIRDPARTY_ROOT}/wince)
		find_package(ZLIB REQUIRED)
		find_path(PNG_INCLUDE_DIR png.h PATHS ${WINCE_PATH}/include CMAKE_FIND_ROOT_PATH_BOTH)
		#message(FATAL_ERROR PNG_INCLUDE_DIR=${PNG_INCLUDE_DIR})
		set(PNG_INCLUDE_DIRS ${PNG_INCLUDE_DIR})
		find_library(PNG_LIBRARIES libpng15.lib PATHS ${WINCE_PATH}/lib CMAKE_FIND_ROOT_PATH_BOTH)
		#message(FATAL_ERROR PNG_LIBRARIES=${PNG_LIBRARIES})
		list(APPEND PNG_LIBRARIES ${ZLIB_LIBRARIES})
		set(PNG_FOUND YES)
	else()
		find_any_standard_lib(PNG $ENV{NG_THIRDPARTY_ROOT} libpng)
		#dll version needs PNG_USE_DLL defined
		if (PNG_FOUND)
			find_package(ZLIB 1.2.5)
			if(ZLIB_FOUND)
				set(PNG_LIBRARIES ${PNG_LIBRARIES} ${ZLIB_LIBRARIES})
			else()
				unset(PNG_INCLUDE_DIRS)
				unset(PNG_LIBRARIES)
			endif()
		endif()
	endif()

	find_any_standard_lib_coda(PNG)
else()
	include(IncludeStandardFindModule)
	include_standard_find_module()
endif()
