if(MSVC OR MINGW)
	include(FindAnyStandardLib)
	if (WIN32 AND CMAKE_COMPILER_IS_GNUCC)
		set(LIBXML2_BASEDIR $ENV{NG_THIRDPARTY_ROOT}/mingw)
		find_path(LIBXML2_INCLUDE_DIR libxml/xpath.h HINTS ${LIBXML2_BASEDIR}/include)
		set(LIBXML2_INCLUDE_DIRS ${LIBXML2_INCLUDE_DIR})
		find_library(LIBXML2_LIBRARIES NAMES libxml2 HINTS ${LIBXML2_BASEDIR}/lib)
	elseif(WINCE)
		set(WINCE_PATH $ENV{NG_THIRDPARTY_ROOT}/wince)
		find_path(LIBXML2_INCLUDE_DIRS libxml/tree.h PATHS ${WINCE_PATH}/include CMAKE_FIND_ROOT_PATH_BOTH)
		set(LIBXML2_INCLUDE_DIR ${LIBXML2_INCLUDE_DIRS})
		#message(FATAL_ERROR LIBXML2_INCLUDE_DIRS=${LIBXML2_INCLUDE_DIRS})
		find_library (LIBXML2_LIBRARIES libxml2.lib PATHS ${WINCE_PATH}/lib CMAKE_FIND_ROOT_PATH_BOTH)
		#message(FATAL_ERROR LIBXML2_LIBRARIES=${LIBXML2_LIBRARIES})
		set(LIBXML2_FOUND YES)
	else ()
		find_any_standard_lib(LibXml2 $ENV{NG_THIRDPARTY_ROOT} libxml2)
		if (LIBXML2_FOUND)
			set(LIBXML2_INCLUDE_DIR ${LIBXML2_INCLUDE_DIRS})
		endif()
		if (LIBXML2_FOUND_STATIC)
			set(LIBXML2_DEFINITIONS -DLIBXML_STATIC)
		endif()
	endif()

	find_any_standard_lib_coda(LibXml2)
else()
	include(IncludeStandardFindModule)
	include_standard_find_module()
endif()
