include(TryFindPackageCfg)
try_find_package_cfg()

if(OGLX_FOUND)
	return()
endif()

if (ANDROID)
	set(OGLX_DEFINITIONS "-DHAVE_EGL -DHAVE_GLES -DHAVE_GLES2")
	set(OGLX_INCLUDE_DIRS "/usr/include")
	set(OGLX_LIBRARIES "-lEGL -lGLESv1_CM -lGLESv2")
	message("ANDROID_NATIVE_API_LEVEL ${ANDROID_NATIVE_API_LEVEL}")
	if (NOT (ANDROID_NATIVE_API_LEVEL LESS 18))
		list(APPEND OGLX_LIBRARIES "-lGLESv3")
		set(OGLX_DEFINITIONS "${OGLX_DEFINITIONS} -DHAVE_GLES3")
	endif()
elseif(IOS)
	find_path(GLES_INCLUDE_DIRS OpenGLES/ES1/gl.h)
	find_path(GLES2_INCLUDE_DIRS OpenGLES/ES2/gl.h)
	set(OGLX_DEFINITIONS "-DHAVE_GLES -DHAVE_GLES2")
	set(OGLX_INCLUDE_DIRS ${GLES_INCLUDE_DIRS} ${GLES2_INCLUDE_DIRS})
	set(OGLX_LIBRARIES "-framework OpenGLES")
elseif(WINCE)
	message("Please fix this (20131030) This could be the same as the general case. Also -DOPENGL_ES2 and -DOGL_GLESv2 must be removed")
	find_path(OGLX_INCLUDE_DIRS GLES2/gl2.h PATHS $ENV{NG_INSTALL_ROOT}/wince/include $ENV{NG_THIRDPARTY_ROOT}/wince/include CMAKE_FIND_ROOT_PATH_BOTH)
	find_library(OGLX_LIBRARY1 libGLESv2.lib PATHS $ENV{NG_INSTALL_ROOT}/wince/lib $ENV{NG_THIRDPARTY_ROOT}/wince/lib CMAKE_FIND_ROOT_PATH_BOTH)
	find_library(OGLX_LIBRARY2 libegl.lib PATHS $ENV{NG_INSTALL_ROOT}/wince/lib $ENV{NG_THIRDPARTY_ROOT}/wince/lib CMAKE_FIND_ROOT_PATH_BOTH)
	if (OGLX_INCLUDE_DIRS AND OGLX_LIBRARY1 AND OGLX_LIBRARY2)
		set(OGLX_LIBRARIES ${OGLX_LIBRARY1} ${OGLX_LIBRARY2})
		set(OGLX_FOUND 1)
		set(OGLX_DEFINITIONS -DOPENGL_ES2 -DOGL_GLESv2 -DHAVE_EGL -DHAVE_GLES2)
	endif()
else()
	if (OPT_USE_GLES)
		macro(find_package_ex pkg)
			find_package(${pkg} QUIET)
			if (NOT ${pkg}_FOUND)
				find_package(${pkg} NO_MODULE QUIET)
			endif()
		endmacro()
		find_package_ex(EGL)
		find_package_ex(GLES)
		find_package_ex(GLES2)
		if (EGL_FOUND)
			set(OGLX_DEFINITIONS "-DHAVE_EGL")
			set(OGLX_INCLUDE_DIRS ${EGL_INCLUDE_DIRS})
			set(OGLX_LIBRARIES ${EGL_LIBRARIES})
		endif()
		if (GLES2_FOUND AND EGL_FOUND)
			list(APPEND OGLX_DEFINITIONS "-DHAVE_GLES2")
			list(APPEND OGLX_INCLUDE_DIRS ${GLES2_INCLUDE_DIRS})
			list(APPEND OGLX_LIBRARIES ${GLES2_LIBRARIES})
		endif()
		if (GLES_FOUND AND EGL_FOUND)
			list(APPEND OGLX_DEFINITIONS "-DHAVE_GLES")
			list(APPEND OGLX_INCLUDE_DIRS ${GLES_INCLUDE_DIRS})
			list(APPEND OGLX_LIBRARIES ${GLES_LIBRARIES})
		endif()
	else()
		find_package(GLEW)
		if (GLEW_FOUND)
			find_package(OpenGL)
			set(OGLX_DEFINITIONS "-DHAVE_GLEW -DHAVE_GL")
			set(OGLX_INCLUDE_DIRS ${GLEW_INCLUDE_DIRS})
			set(OGLX_LIBRARIES ${GLEW_LIBRARIES} ${OPENGL_gl_LIBRARY})
		else()
			find_package(OpenGL)
			if (OPENGL_FOUND)
				set(OGLX_DEFINITIONS "-DHAVE_GL")
				set(OGLX_INCLUDE_DIRS ${OPENGL_INCLUDE_DIR})
				set(OGLX_LIBRARIES ${OPENGL_gl_LIBRARY})
			endif()
		endif()
	endif()
endif()
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(OGLX DEFAULT_MSG OGLX_LIBRARIES OGLX_INCLUDE_DIRS)
mark_as_advanced(OGLX_LIBRARIES OGLX_INCLUDE_DIRS)
