function(mklink SOURCE DESTINATION)
    if(EXISTS "${SOURCE}")
        if("$ENV{COMSPEC}" STREQUAL "")
            execute_process(COMMAND "ln" "-fns" "${SOURCE}" "${DESTINATION}")
        else()
            string(REPLACE "/" "\\" SRC ${SOURCE})
            string(REPLACE "/" "\\" DST ${DESTINATION})
            execute_process(COMMAND "$ENV{COMSPEC}" "/C rmdir /Q ${DST}" OUTPUT_QUIET ERROR_QUIET)
            execute_process(COMMAND "$ENV{COMSPEC}" "/C del /F /Q ${DST}" OUTPUT_QUIET ERROR_QUIET)
            if( IS_DIRECTORY "${SRC}")
                #message(STATUS "$ENV{COMSPEC} /C mklink /J ${DST} ${SRC}")
                execute_process(COMMAND "$ENV{COMSPEC}" "/C" "mklink" "/J" "${DST}" "${SRC}" OUTPUT_QUIET)
            else()
                #message(STATUS "$ENV{COMSPEC} /C mklink /H ${DST} ${SRC}")
                execute_process(COMMAND "$ENV{COMSPEC}" "/C" "mklink" "/H" "${DST}" "${SRC}" OUTPUT_QUIET)
            endif()
        endif()
    endif()
endfunction()

function(link_all_files DIRECTORY DESTINATION)
    file(GLOB TARGETS RELATIVE ${DIRECTORY} ${DIRECTORY}/*)
    foreach(target ${TARGETS})
        mklink("${DIRECTORY}/${target}" "${DESTINATION}/${target}")
    endforeach()
endfunction()
