function(printvar_core printvar.x printvar.name)
	list(LENGTH ${printvar.x} printvar.l)
	if(printvar.l EQUAL 0)
		message(STATUS "'${printvar.name}' is empty")
	elseif(printvar.l EQUAL 1)
		message(STATUS "'${printvar.name}' = '${${printvar.x}}'")
	else()
		message(STATUS "'${printvar.name}' is a list of ${printvar.l} items:")
		math(EXPR printvar.l_minus_1 "${printvar.l} - 1")
		foreach(printvar.i RANGE ${printvar.l_minus_1})
			list(GET ${printvar.x} ${printvar.i} printvar.v)
			message(STATUS "    #${printvar.i}: '${printvar.v}'")
		endforeach()
	endif()
endfunction()

function(printvar printvar.x)
	printvar_core(${printvar.x} ${printvar.x})
endfunction()

function(printenvvar printvar.x)
	set(ENV_${printvar.x} $ENV{${printvar.x}})
	printvar_core(ENV_${printvar.x} "ENV{${printvar.x}}")
endfunction()
