/*
 * Copyright (c) 2005-2025, Kishonti Ltd
 * SPDX-License-Identifier: BSD-3-Clause
 * This file is part of GFXBench. See the top-level LICENSE file for details.
 */
package net.kishonti.systeminfo;

import java.util.HashMap;
import javax.microedition.khronos.opengles.GL10;
import android.annotation.TargetApi;
import android.opengl.GLES20;
import android.opengl.GLES30;
import android.os.Build;

@TargetApi(Build.VERSION_CODES.JELLY_BEAN_MR2)
class InfoGL {

	final private GL10 mGL;
	final HashMap<String, String> mData;
	private int[] res = new int[1];

	public InfoGL(GL10 gl, HashMap<String, String> data) {
		mGL = gl;
		mData = data;
	}

	public void update() {

		if (android.os.Build.VERSION.SDK_INT >= 18) {

			addDetail("GL_MAX_3D_TEXTURE_SIZE", GLES30.GL_MAX_3D_TEXTURE_SIZE);
			addDetail("GL_MAX_ARRAY_TEXTURE_LAYERS", GLES30.GL_MAX_ARRAY_TEXTURE_LAYERS);
			addDetail("GL_MAX_COLOR_ATTACHMENTS", GLES30.GL_MAX_COLOR_ATTACHMENTS);
			addDetail("GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS", GLES30.GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS);
			addDetail("GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS", GLES20.GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS);
			addDetail("GL_MAX_COMBINED_UNIFORM_BLOCKS", GLES30.GL_MAX_COMBINED_UNIFORM_BLOCKS);
			addDetail("GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS", GLES30.GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS);
			addDetail("GL_MAX_CUBE_MAP_TEXTURE_SIZE", GLES20.GL_MAX_CUBE_MAP_TEXTURE_SIZE);
			addDetail("GL_MAX_CUBE_MAP_TEXTURE_SIZE", GLES20.GL_MAX_CUBE_MAP_TEXTURE_SIZE);
			addDetail("GL_MAX_DRAW_BUFFERS", GLES30.GL_MAX_DRAW_BUFFERS);
			addDetail("GL_MAX_ELEMENTS_VERTICES", GLES30.GL_MAX_ELEMENTS_VERTICES);
			addDetail("GL_MAX_ELEMENT_INDEX", GLES30.GL_MAX_ELEMENT_INDEX);
			addDetail("GL_MAX_ELEMENTS_INDICES", GLES30.GL_MAX_ELEMENTS_INDICES);
			addDetail("GL_MAX_FRAGMENT_INPUT_COMPONENTS", GLES30.GL_MAX_FRAGMENT_INPUT_COMPONENTS);
			addDetail("GL_MAX_FRAGMENT_UNIFORM_BLOCKS", GLES30.GL_MAX_FRAGMENT_UNIFORM_BLOCKS);
			addDetail("GL_MAX_FRAGMENT_UNIFORM_VECTORS", GLES20.GL_MAX_FRAGMENT_UNIFORM_VECTORS);
			addDetail("GL_MAX_FRAGMENT_UNIFORM_COMPONENTS", GLES30.GL_MAX_FRAGMENT_UNIFORM_COMPONENTS);
			addDetail("GL_MAX_PROGRAM_TEXEL_OFFSET", GLES30.GL_MAX_PROGRAM_TEXEL_OFFSET);
			addDetail("GL_MAX_RENDERBUFFER_SIZE", GLES20.GL_MAX_RENDERBUFFER_SIZE);
			addDetail("GL_MAX_SAMPLES", GLES30.GL_MAX_SAMPLES);
			addDetail("GL_MAX_SERVER_WAIT_TIMEOUT", GLES30.GL_MAX_SERVER_WAIT_TIMEOUT);
			addDetail("GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS", GLES30.GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS);
			addDetail("GL_MAX_UNIFORM_BLOCK_SIZE", GLES30.GL_MAX_UNIFORM_BLOCK_SIZE);
			addDetail("GL_MAX_UNIFORM_BUFFER_BINDINGS", GLES30.GL_MAX_UNIFORM_BUFFER_BINDINGS);
			addDetail("GL_MAX_VARYING_COMPONENTS", GLES30.GL_MAX_VARYING_COMPONENTS);
			addDetail("GL_MAX_VARYING_VECTORS", GLES20.GL_MAX_VARYING_VECTORS);
			addDetail("GL_MAX_VERTEX_ATTRIBS", GLES20.GL_MAX_VERTEX_ATTRIBS);
			addDetail("GL_MAX_VERTEX_OUTPUT_COMPONENTS", GLES30.GL_MAX_VERTEX_OUTPUT_COMPONENTS);
			addDetail("GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS", GLES20.GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS);
			addDetail("GL_MAX_VERTEX_UNIFORM_BLOCKS", GLES30.GL_MAX_VERTEX_UNIFORM_BLOCKS);
			addDetail("GL_MAX_VERTEX_UNIFORM_VECTORS", GLES20.GL_MAX_VERTEX_UNIFORM_VECTORS);
			addDetail("GL_MAX_VERTEX_UNIFORM_COMPONENTS", GLES30.GL_MAX_VERTEX_UNIFORM_COMPONENTS);
			addDetail("GL_MAX_ARRAY_TEXTURE_LAYERS", GLES30.GL_MAX_ARRAY_TEXTURE_LAYERS);
			addDetail("GL_MAX_TEXTURE_IMAGE_UNITS", GLES20.GL_MAX_TEXTURE_IMAGE_UNITS);
			addDetail("GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS", GLES30.GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS);
			addDetail("GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS", GLES30.GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS);
			addDetail("GL_MIN_PROGRAM_TEXEL_OFFSET", GLES30.GL_MIN_PROGRAM_TEXEL_OFFSET);
		}

		addDetail("GL_ALPHA_BITS", GL10.GL_ALPHA_BITS);
		addDetail("GL_RED_BITS", GL10.GL_RED_BITS);
		addDetail("GL_GREEN_BITS", GL10.GL_GREEN_BITS);
		addDetail("GL_BLUE_BITS", GL10.GL_BLUE_BITS);
		addDetail("GL_DEPTH_BITS", GL10.GL_DEPTH_BITS);
		addDetail("GL_STENCIL_BITS", GL10.GL_STENCIL_BITS);
		addDetail("GL_NUM_COMPRESSED_TEXTURE_FORMATS", GL10.GL_NUM_COMPRESSED_TEXTURE_FORMATS);
		addDetail("GL_MAX_TEXTURE_SIZE", GL10.GL_MAX_TEXTURE_SIZE);
	}

	private void addDetail(String keyString, int keyInteger) {
		mGL.glGetIntegerv(keyInteger, res, 0);
		mData.put(keyString, "" + res[0]);
	}

}
