/*
 * Copyright (c) 2005-2025, Kishonti Ltd
 * SPDX-License-Identifier: BSD-3-Clause
 * This file is part of GFXBench. See the top-level LICENSE file for details.
 */
#ifdef _WIN32
#ifdef WINGDIAPI
#undef WINGDIAPI
#endif
#ifdef APIENTRY
#undef APIENTRY
#endif
#include <windows.h>
#endif

#include "cudainfocollector.h"

#include "jsonvisitor.h"
#include "cudaw/cudaw.h"
#include "ng/log.h"

using namespace sysinf;


namespace {



void addAttribute(
        CUdevice device,
        CUdevice_attribute attribute,
        const char* name,
        CudaDeviceInfo& deviceInfo)
{
    int value = 0;
    CUresult infoStatus = cuDeviceGetAttribute(&value, attribute, device);
    if (infoStatus == CUDA_SUCCESS) {
        deviceInfo.attributes.push_back(std::make_pair(name, value));
    }
}



}



#define ADD_ATTRIBUTE(attribute) addAttribute(device, attribute, #attribute, deviceInfo)



void sysinf::collectCudaInfo(SystemInfo &systemInfo)
{
    systemInfo.hasCuda = false;
    systemInfo.cudaInfo.devices.clear();

    CUresult infoStatus = CUDA_ERROR_UNKNOWN;
    if (!cudawInitialized()) {
        infoStatus = cudawInit(0, 0);
        if (infoStatus != CUDA_SUCCESS) {
            NGLOG_DEBUG("cudawInit failed: %s", infoStatus);
            return;
        }
    }

    infoStatus = cuInit(0);
    if (infoStatus != CUDA_SUCCESS) {
        NGLOG_DEBUG("cuInit failed: %s", infoStatus);
        return;
    }

    infoStatus = cuDriverGetVersion(&systemInfo.cudaInfo.driverVersion);
    assert(infoStatus == CUDA_SUCCESS);

    int deviceCount;
    infoStatus = cuDeviceGetCount(&deviceCount);
    assert(infoStatus == CUDA_SUCCESS);

    for(int i = 0; i < deviceCount; ++i)
    {
        CudaDeviceInfo deviceInfo;
        deviceInfo.driverVersion = systemInfo.cudaInfo.driverVersion;

        CUdevice device;
        infoStatus = cuDeviceGet(&device, i) ;
        assert(infoStatus == CUDA_SUCCESS);

        char name[256];
        infoStatus = cuDeviceGetName(name, sizeof(name) - 1, device);
        assert(infoStatus == CUDA_SUCCESS);
        deviceInfo.name = name;

		int ccMajor = 0, ccMinor = 0;
		infoStatus = cuDeviceComputeCapability(&ccMajor, &ccMinor, device);
		assert(infoStatus == CUDA_SUCCESS);
		deviceInfo.ccMajor = ccMajor;
		deviceInfo.ccMinor = ccMinor;

        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_BLOCK);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_X);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Y);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAX_BLOCK_DIM_Z);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_X);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Y);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAX_GRID_DIM_Z);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_BLOCK);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_SHARED_MEMORY_PER_BLOCK);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_TOTAL_CONSTANT_MEMORY);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_WARP_SIZE);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAX_PITCH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_BLOCK);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_REGISTERS_PER_BLOCK);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_CLOCK_RATE);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_TEXTURE_ALIGNMENT);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_GPU_OVERLAP);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_KERNEL_EXEC_TIMEOUT);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_INTEGRATED);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_CAN_MAP_HOST_MEMORY);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_COMPUTE_MODE);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_HEIGHT);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_HEIGHT);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_DEPTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_HEIGHT);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LAYERED_LAYERS);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_HEIGHT);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_ARRAY_NUMSLICES);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_SURFACE_ALIGNMENT);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_CONCURRENT_KERNELS);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_ECC_ENABLED);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_PCI_BUS_ID);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_PCI_DEVICE_ID);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_TCC_DRIVER);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MEMORY_CLOCK_RATE);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_GLOBAL_MEMORY_BUS_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_L2_CACHE_SIZE);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAX_THREADS_PER_MULTIPROCESSOR);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_ASYNC_ENGINE_COUNT);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_UNIFIED_ADDRESSING);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LAYERED_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LAYERED_LAYERS);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_CAN_TEX2D_GATHER);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_GATHER_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_GATHER_HEIGHT);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_WIDTH_ALTERNATE);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_HEIGHT_ALTERNATE);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE3D_DEPTH_ALTERNATE);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_PCI_DOMAIN_ID);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_TEXTURE_PITCH_ALIGNMENT);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_LAYERED_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURECUBEMAP_LAYERED_LAYERS);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_HEIGHT);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_HEIGHT);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE3D_DEPTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_LAYERED_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE1D_LAYERED_LAYERS);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_HEIGHT);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACE2D_LAYERED_LAYERS);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_LAYERED_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_SURFACECUBEMAP_LAYERED_LAYERS);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_LINEAR_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_HEIGHT);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_LINEAR_PITCH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_MIPMAPPED_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE2D_MIPMAPPED_HEIGHT);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAXIMUM_TEXTURE1D_MIPMAPPED_WIDTH);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_STREAM_PRIORITIES_SUPPORTED);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_GLOBAL_L1_CACHE_SUPPORTED);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_LOCAL_L1_CACHE_SUPPORTED);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAX_SHARED_MEMORY_PER_MULTIPROCESSOR);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MAX_REGISTERS_PER_MULTIPROCESSOR);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MANAGED_MEMORY);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD);
        ADD_ATTRIBUTE(CU_DEVICE_ATTRIBUTE_MULTI_GPU_BOARD_GROUP_ID);

        systemInfo.cudaInfo.devices.push_back(deviceInfo);
    }

    systemInfo.hasCuda = true;
}
