#logger
set(OPT_NGLOG_SEVERITY_LIST
	NGLOG_SEVERITY_ANY
	NGLOG_SEVERITY_TRACE
	NGLOG_SEVERITY_DEBUG
	NGLOG_SEVERITY_INFO
	NGLOG_SEVERITY_WARN
	NGLOG_SEVERITY_ERROR
	NGLOG_SEVERITY_FATAL
	NGLOG_SEVERITY_NONE
	"<not set>")
list(GET OPT_NGLOG_SEVERITY_LIST -1 OPT_NGLOG_ENABLE_DEFAULT)
set(OPT_NGLOG_ENABLE ${OPT_NGLOG_ENABLE_DEFAULT} CACHE STRING "only logging messages (NGLOG_...) above this level will be compiled into the binary")
set_property(CACHE OPT_NGLOG_ENABLE PROPERTY STRINGS ${OPT_NGLOG_SEVERITY_LIST})

if (NOT ${OPT_NGLOG_ENABLE} STREQUAL ${OPT_NGLOG_ENABLE_DEFAULT})
	add_definitions(-DNGLOG_ENABLE=${OPT_NGLOG_ENABLE})
endif()
