if (NOT $ENV{CC} STREQUAL "")
	set(CMAKE_C_COMPILER "$ENV{CC}" CACHE STRING "gcc")
endif()

if (NOT $ENV{CXX} STREQUAL "")
	set(CMAKE_CXX_COMPILER "$ENV{CXX}" CACHE STRING "g++")
endif()

if (NOT $ENV{SYSROOT} STREQUAL "")
	set( CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER )
	set( CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY )
	set( CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
	set( CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )

	set(CMAKE_FIND_ROOT_PATH "$ENV{SYSROOT}" "${CMAKE_PREFIX_PATH}" "${CMAKE_INSTALL_PREFIX}")
	set(CMAKE_SYSROOT "$ENV{SYSROOT}" CACHE STRING "sysroot")
endif()

set(CMAKE_CPP_FLAGS "$ENV{CPPFLAGS}" CACHE STRING "c flags" )
set(CMAKE_CXX_FLAGS "$ENV{CXXFLAGS} -fPIC -fvisibility=hidden " CACHE STRING "c++ flags" )
set(CMAKE_C_FLAGS "$ENV{CFLAGS} -fPIC -fvisibility=hidden " CACHE STRING "c flags" )
set(CMAKE_EXE_LINKER_FLAGS "$ENV{LDFLAGS} " CACHE STRING "ld flags")

