/*
 * Copyright (c) 2005-2025, Kishonti Ltd
 * SPDX-License-Identifier: BSD-3-Clause
 * This file is part of GFXBench. See the top-level LICENSE file for details.
 */
#ifndef CLEW_FUNCTION_DEFINES_H
#define CLEW_FUNCTION_DEFINES_H

#define clGetPlatformIDs								FUNC_clGetPlatformIDs
#define clGetPlatformInfo                               FUNC_clGetPlatformInfo
#define clGetDeviceIDs                                  FUNC_clGetDeviceIDs
#define clGetDeviceInfo                                 FUNC_clGetDeviceInfo
#define clCreateContext                                 FUNC_clCreateContext
#define clCreateContextFromType                         FUNC_clCreateContextFromType
#define clRetainContext                                 FUNC_clRetainContext
#define clReleaseContext                                FUNC_clReleaseContext
#define clGetContextInfo                                FUNC_clGetContextInfo
#define clCreateCommandQueue                            FUNC_clCreateCommandQueue
#define clRetainCommandQueue                            FUNC_clRetainCommandQueue
#define clReleaseCommandQueue                           FUNC_clReleaseCommandQueue
#define clGetCommandQueueInfo                           FUNC_clGetCommandQueueInfo
#define clCreateBuffer                                  FUNC_clCreateBuffer
#define clCreateImage2D                                 FUNC_clCreateImage2D
#define clCreateImage3D                                 FUNC_clCreateImage3D
#define clRetainMemObject                               FUNC_clRetainMemObject
#define clReleaseMemObject                              FUNC_clReleaseMemObject
#define clGetSupportedImageFormats                      FUNC_clGetSupportedImageFormats
#define clGetMemObjectInfo                              FUNC_clGetMemObjectInfo
#define clGetImageInfo                                  FUNC_clGetImageInfo
#define clCreateSampler                                 FUNC_clCreateSampler
#define clRetainSampler                                 FUNC_clRetainSampler
#define clReleaseSampler                                FUNC_clReleaseSampler
#define clGetSamplerInfo                                FUNC_clGetSamplerInfo
#define clCreateProgramWithSource                       FUNC_clCreateProgramWithSource
#define clCreateProgramWithBinary                       FUNC_clCreateProgramWithBinary
#define clRetainProgram                                 FUNC_clRetainProgram
#define clReleaseProgram                                FUNC_clReleaseProgram
#define clBuildProgram                                  FUNC_clBuildProgram
#define clGetProgramInfo                                FUNC_clGetProgramInfo
#define clGetProgramBuildInfo                           FUNC_clGetProgramBuildInfo
#define clCreateKernel                                  FUNC_clCreateKernel
#define clCreateKernelsInProgram                        FUNC_clCreateKernelsInProgram
#define clRetainKernel                                  FUNC_clRetainKernel
#define clReleaseKernel                                 FUNC_clReleaseKernel
#define clSetKernelArg                                  FUNC_clSetKernelArg
#define clGetKernelInfo                                 FUNC_clGetKernelInfo
#define clGetKernelWorkGroupInfo                        FUNC_clGetKernelWorkGroupInfo
#define clWaitForEvents                                 FUNC_clWaitForEvents
#define clGetEventInfo                                  FUNC_clGetEventInfo
#define clRetainEvent                                   FUNC_clRetainEvent
#define clReleaseEvent                                  FUNC_clReleaseEvent
#define clGetEventProfilingInfo                         FUNC_clGetEventProfilingInfo
#define clFlush                                         FUNC_clFlush
#define clFinish                                        FUNC_clFinish
#define clEnqueueReadBuffer                             FUNC_clEnqueueReadBuffer
#define clEnqueueWriteBuffer                            FUNC_clEnqueueWriteBuffer
#define clEnqueueCopyBuffer                             FUNC_clEnqueueCopyBuffer
#define clEnqueueReadImage                              FUNC_clEnqueueReadImage
#define clEnqueueWriteImage                             FUNC_clEnqueueWriteImage
#define clEnqueueCopyImage                              FUNC_clEnqueueCopyImage
#define clEnqueueCopyImageToBuffer                      FUNC_clEnqueueCopyImageToBuffer
#define clEnqueueCopyBufferToImage                      FUNC_clEnqueueCopyBufferToImage
#define clEnqueueMapBuffer                              FUNC_clEnqueueMapBuffer
#define clEnqueueMapImage                               FUNC_clEnqueueMapImage
#define clEnqueueUnmapMemObject                         FUNC_clEnqueueUnmapMemObject
#define clEnqueueNDRangeKernel                          FUNC_clEnqueueNDRangeKernel
#define clEnqueueNativeKernel                           FUNC_clEnqueueNativeKernel
#define clEnqueueMarker                                 FUNC_clEnqueueMarker
#define clEnqueueWaitForEvents                          FUNC_clEnqueueWaitForEvents
#define clEnqueueBarrier                                FUNC_clEnqueueBarrier
#define clEnqueueTask                                   FUNC_clEnqueueTask
#define clUnloadCompiler                                FUNC_clUnloadCompiler
#define clGetExtensionFunctionAddress                   FUNC_clGetExtensionFunctionAddress
#define clCreateSubBuffer                               FUNC_clCreateSubBuffer
#define clSetMemObjectDestructorCallback                FUNC_clSetMemObjectDestructorCallback
#define clCreateUserEvent                               FUNC_clCreateUserEvent
#define clSetUserEventStatus                            FUNC_clSetUserEventStatus
#define clSetEventCallback                              FUNC_clSetEventCallback
#define clEnqueueReadBufferRect                         FUNC_clEnqueueReadBufferRect
#define clEnqueueWriteBufferRect                        FUNC_clEnqueueWriteBufferRect
#define clEnqueueCopyBufferRect                         FUNC_clEnqueueCopyBufferRect
#define clCreateSubDevices                              FUNC_clCreateSubDevices
#define clRetainDevice                                  FUNC_clRetainDevice
#define clReleaseDevice                                 FUNC_clReleaseDevice
#define clCreateImage                                   FUNC_clCreateImage
#define clCreateProgramWithBuiltInKernels               FUNC_clCreateProgramWithBuiltInKernels
#define clCompileProgram                                FUNC_clCompileProgram
#define clLinkProgram                                   FUNC_clLinkProgram
#define clUnloadPlatformCompiler                        FUNC_clUnloadPlatformCompiler
#define clGetKernelArgInfo                              FUNC_clGetKernelArgInfo
#define clEnqueueFillBuffer                             FUNC_clEnqueueFillBuffer
#define clEnqueueFillImage                              FUNC_clEnqueueFillImage
#define clEnqueueMigrateMemObjects                      FUNC_clEnqueueMigrateMemObjects
#define clEnqueueMarkerWithWaitList                     FUNC_clEnqueueMarkerWithWaitList
#define clEnqueueBarrierWithWaitList                    FUNC_clEnqueueBarrierWithWaitList
#define clGetExtensionFunctionAddressForPlatform        FUNC_clGetExtensionFunctionAddressForPlatform
#define clCreateCommandQueueWithProperties              FUNC_clCreateCommandQueueWithProperties
#define clCreatePipe                                    FUNC_clCreatePipe
#define clGetPipeInfo                                   FUNC_clGetPipeInfo
#define clSVMAlloc                                      FUNC_clSVMAlloc
#define clSVMFree                                       FUNC_clSVMFree
#define clCreateSamplerWithProperties                   FUNC_clCreateSamplerWithProperties
#define clSetKernelArgSVMPointer                        FUNC_clSetKernelArgSVMPointer
#define clSetKernelExecInfo                             FUNC_clSetKernelExecInfo
#define clEnqueueSVMFree                                FUNC_clEnqueueSVMFree
#define clEnqueueSVMMemcpy                              FUNC_clEnqueueSVMMemcpy
#define clEnqueueSVMMemFill                             FUNC_clEnqueueSVMMemFill
#define clEnqueueSVMMap                                 FUNC_clEnqueueSVMMap
#define clEnqueueSVMUnmap                               FUNC_clEnqueueSVMUnmap
#define clCreateFromGLBuffer                            FUNC_clCreateFromGLBuffer
#define clCreateFromGLRenderbuffer                      FUNC_clCreateFromGLRenderbuffer
#define clGetGLObjectInfo                               FUNC_clGetGLObjectInfo
#define clGetGLTextureInfo                              FUNC_clGetGLTextureInfo
#define clEnqueueAcquireGLObjects                       FUNC_clEnqueueAcquireGLObjects
#define clEnqueueReleaseGLObjects                       FUNC_clEnqueueReleaseGLObjects
#define clCreateFromGLTexture2D                         FUNC_clCreateFromGLTexture2D
#define clCreateFromGLTexture3D                         FUNC_clCreateFromGLTexture3D
#define clGetGLContextInfoKHR                           FUNC_clGetGLContextInfoKHR
#define clCreateFromGLTexture                           FUNC_clCreateFromGLTexture
#define clCreateFromEGLImageKHR							FUNC_clCreateFromEGLImageKHR
#define clEnqueueAcquireEGLObjectsKHR					FUNC_clEnqueueAcquireEGLObjectsKHR
#define clEnqueueReleaseEGLObjectsKHR					FUNC_clEnqueueReleaseEGLObjectsKHR
#define clCreateEventFromEGLSyncKHR						FUNC_clCreateEventFromEGLSyncKHR

#endif //CLEW_FUNCTION_DEFINES_H
