function(copy_all_config_jsons)
    file(MAKE_DIRECTORY ${TFW_PACKAGE_DIR}/config)
    file(GLOB_RECURSE CONFIGS "${CMAKE_CURRENT_LIST_DIR}/resources/*/*/config/*.json")
    
    foreach(config ${CONFIGS})
        file(COPY "${config}" DESTINATION ${TFW_PACKAGE_DIR}/config NO_SOURCE_PERMISSIONS)
    endforeach()
endfunction()


file(MAKE_DIRECTORY ${TFW_PACKAGE_DIR}/config)
file(MAKE_DIRECTORY ${TFW_PACKAGE_DIR}/data/gfx)
file(GLOB_RECURSE CONFIGS "${CMAKE_CURRENT_LIST_DIR}/resources/${PRODUCT_ID}/config/*.json")
file(MAKE_DIRECTORY ${TFW_PACKAGE_DIR}/plugins)
foreach(config ${CONFIGS})
    file(COPY "${config}" DESTINATION ${TFW_PACKAGE_DIR}/config NO_SOURCE_PERMISSIONS)
endforeach()

if("${APPLICATION_TYPE}" STREQUAL "gui")

    file(GLOB ALL_IMAGES "${CMAKE_CURRENT_LIST_DIR}/resources/${PRODUCT_ID}/images")
    file(COPY ${ALL_IMAGES} DESTINATION "${TFW_PACKAGE_DIR}" NO_SOURCE_PERMISSIONS)

    file(GLOB TESTLISTS "${CMAKE_CURRENT_LIST_DIR}/resources/${PRODUCT_ID}/testlist_*.*.json")
    file(COPY ${TESTLISTS} DESTINATION "${TFW_PACKAGE_DIR}" NO_SOURCE_PERMISSIONS)

    if(${CMAKE_SYSTEM_NAME} STREQUAL "WindowsPhone")
        file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/${PRODUCT_ID}/benchmark_tests.json" DESTINATION ${TFW_PACKAGE_DIR} NO_SOURCE_PERMISSIONS)
        file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/${PRODUCT_ID}/wp/images" DESTINATION ${TFW_PACKAGE_DIR} NO_SOURCE_PERMISSIONS)
        file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/${PRODUCT_ID}/wp/theme" DESTINATION ${TFW_PACKAGE_DIR} NO_SOURCE_PERMISSIONS)
    elseif(${CMAKE_SYSTEM_NAME} STREQUAL "WindowsStore")
        file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/${PRODUCT_ID}/benchmark_tests.json" DESTINATION ${TFW_PACKAGE_DIR} NO_SOURCE_PERMISSIONS)
        file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/${PRODUCT_ID}/rt/images" DESTINATION ${TFW_PACKAGE_DIR} NO_SOURCE_PERMISSIONS)
        file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/${PRODUCT_ID}/rt/theme" DESTINATION ${TFW_PACKAGE_DIR} NO_SOURCE_PERMISSIONS)
    endif()

    if(NOT OPT_COMMUNITY_BUILD)
        if( ${PRODUCT_ID} STREQUAL "gfxbench" )
            copy_all_config_jsons()
        else() 
            file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/${PRODUCT_ID}/testlist_corporate.json" DESTINATION ${TFW_PACKAGE_DIR} NO_SOURCE_PERMISSIONS)
        endif()
    endif()

endif()

set(ver "${BENCHMARK_VERSION_MAJOR}.${BENCHMARK_VERSION_MINOR}")
if (BUNDLE_DATA)

    if ("${PRODUCT_ID}" STREQUAL "gfxbench_gl")

        if (DEFINED ENV{GFX_TESTS} AND "$ENV{GFX_TESTS}" STREQUAL "all")

                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.20"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.30"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.31"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.4"     DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/common.31"     DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/lowlevel"      DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS) 
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/lowlevel2"     DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/lowlevel4"     DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)

        else()

            if (${ver} STREQUAL "3.0")
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.20"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.30"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/lowlevel"      DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
            elseif(${ver} STREQUAL "3.1")
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.20"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.30"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.31"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/common.31"     DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/lowlevel2"     DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
            elseif(${ver} STREQUAL "4.0")
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.20"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.30"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.31"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/lowlevel"      DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/lowlevel2"     DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/lowlevel4"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/common.31"     DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.4"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
            elseif(${ver} STREQUAL "5.0")
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.20"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.30"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.31"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/lowlevel"      DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)                
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/lowlevel2"     DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/lowlevel4"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/common.31"     DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
                file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.4"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)                
            endif()

        endif()

    elseif ("${PRODUCT_ID}" STREQUAL "gfxbench_dx")
        file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_dx"     DESTINATION ${TFW_PACKAGE_DIR}/data/gfx)
        file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_dx_bin" DESTINATION ${TFW_PACKAGE_DIR}/data/gfx)
    elseif ("${PRODUCT_ID}" STREQUAL "gfxbench_metal")
        file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_mtl"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx)
        
        # workaround
        if(OPT_COMMUNITY_BUILD)
            file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.20"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
            file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.30"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
            file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.31"    DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
            file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/lowlevel"      DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
            file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/lowlevel2"     DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
            file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/lowlevel4"     DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
            file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/common.31"     DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
            file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/shaders.4"     DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
            file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/data/gfx/shaders_40/community"     DESTINATION ${TFW_PACKAGE_DIR}/data/gfx/shaders_40 NO_SOURCE_PERMISSIONS)
        endif()
     endif()
endif()
