
if (${BENCHMARK_VERSION_MAJOR} LESS 5)
    include(../gfxbench40/tfw_package.cmake)
    return()
endif()

file(MAKE_DIRECTORY ${TFW_PACKAGE_DIR}/data/gfx)
file(MAKE_DIRECTORY ${TFW_PACKAGE_DIR}/config)
file(MAKE_DIRECTORY ${TFW_PACKAGE_DIR}/plugins)
file(MAKE_DIRECTORY ${TFW_PACKAGE_DIR}/images)

if (DEFINED ENV{GFX_TESTS} AND "$ENV{GFX_TESTS}" STREQUAL "all")
	file(GLOB_RECURSE CONFIGS "${CMAKE_CURRENT_LIST_DIR}/resources/*/*/config/*.json")
	
	foreach(config ${CONFIGS})
		file(COPY "${config}" DESTINATION ${TFW_PACKAGE_DIR}/config NO_SOURCE_PERMISSIONS)
	endforeach()
endif()

if("${APPLICATION_TYPE}" STREQUAL "gui")
	if(OPT_COMMUNITY_BUILD)
		if (PRODUCT_ID STREQUAL "gfxbench" AND ANDROID)
			file(GLOB TESTLISTS "${CMAKE_CURRENT_LIST_DIR}/resources/${PRODUCT_ID}/android/testlist_*.*.json")
		else()
			file(GLOB TESTLISTS "${CMAKE_CURRENT_LIST_DIR}/resources/${PRODUCT_ID}/testlist_*.*.json")
		endif()
		file(COPY ${TESTLISTS} DESTINATION "${TFW_PACKAGE_DIR}" NO_SOURCE_PERMISSIONS)
	else()
		if (PRODUCT_ID STREQUAL "gfxbench" AND ANDROID)
			file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/${PRODUCT_ID}/android/${BENCHMARK_VERSION_MAJOR}.${BENCHMARK_VERSION_MINOR}/testlist_corporate.json" DESTINATION ${TFW_PACKAGE_DIR} NO_SOURCE_PERMISSIONS)
		else()
			file(COPY "${CMAKE_CURRENT_LIST_DIR}/resources/${PRODUCT_ID}/${BENCHMARK_VERSION_MAJOR}.${BENCHMARK_VERSION_MINOR}/testlist_corporate.json" DESTINATION ${TFW_PACKAGE_DIR} NO_SOURCE_PERMISSIONS)
		endif()
	endif()
endif()
