/*
 * Copyright (c) 2005-2025, Kishonti Ltd
 * SPDX-License-Identifier: BSD-3-Clause
 * This file is part of GFXBench. See the top-level LICENSE file for details.
 */
#include "gl_wrapper_gl31_gl3platform.h"

typedef khronos_int8_t GLbyte;
typedef khronos_float_t GLclampf;
typedef khronos_int32_t GLfixed;
typedef short GLshort;
typedef unsigned short GLushort;
typedef void GLvoid;
typedef struct __GLsync *GLsync;
typedef khronos_int64_t GLint64;
typedef khronos_uint64_t GLuint64;
typedef unsigned int GLenum;
typedef unsigned int GLuint;
typedef char GLchar;
typedef khronos_float_t GLfloat;
typedef khronos_ssize_t GLsizeiptr;
typedef khronos_intptr_t GLintptr;
typedef unsigned int GLbitfield;
typedef int GLint;
typedef unsigned char GLboolean;
typedef int GLsizei;
typedef khronos_uint8_t GLubyte;
void GL_APIENTRY glActiveTexture (GLenum texture);
void GL_APIENTRY glAttachShader (GLuint program, GLuint shader);
void GL_APIENTRY glBindAttribLocation (GLuint program, GLuint index, const GLchar *name);
void GL_APIENTRY glBindBuffer (GLenum target, GLuint buffer);
void GL_APIENTRY glBindFramebuffer (GLenum target, GLuint framebuffer);
void GL_APIENTRY glBindRenderbuffer (GLenum target, GLuint renderbuffer);
void GL_APIENTRY glBindTexture (GLenum target, GLuint texture);
void GL_APIENTRY glBlendColor (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void GL_APIENTRY glBlendEquation (GLenum mode);
void GL_APIENTRY glBlendEquationSeparate (GLenum modeRGB, GLenum modeAlpha);
void GL_APIENTRY glBlendFunc (GLenum sfactor, GLenum dfactor);
void GL_APIENTRY glBlendFuncSeparate (GLenum sfactorRGB, GLenum dfactorRGB, GLenum sfactorAlpha, GLenum dfactorAlpha);
void GL_APIENTRY glBufferData (GLenum target, GLsizeiptr size, const void *data, GLenum usage);
void GL_APIENTRY glBufferSubData (GLenum target, GLintptr offset, GLsizeiptr size, const void *data);
GLenum GL_APIENTRY glCheckFramebufferStatus (GLenum target);
void GL_APIENTRY glClear (GLbitfield mask);
void GL_APIENTRY glClearColor (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
void GL_APIENTRY glClearDepthf (GLfloat d);
void GL_APIENTRY glClearStencil (GLint s);
void GL_APIENTRY glColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
void GL_APIENTRY glCompileShader (GLuint shader);
void GL_APIENTRY glCompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data);
void GL_APIENTRY glCompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data);
void GL_APIENTRY glCopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
void GL_APIENTRY glCopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
GLuint GL_APIENTRY glCreateProgram (void);
GLuint GL_APIENTRY glCreateShader (GLenum type);
void GL_APIENTRY glCullFace (GLenum mode);
void GL_APIENTRY glDeleteBuffers (GLsizei n, const GLuint *buffers);
void GL_APIENTRY glDeleteFramebuffers (GLsizei n, const GLuint *framebuffers);
void GL_APIENTRY glDeleteProgram (GLuint program);
void GL_APIENTRY glDeleteRenderbuffers (GLsizei n, const GLuint *renderbuffers);
void GL_APIENTRY glDeleteShader (GLuint shader);
void GL_APIENTRY glDeleteTextures (GLsizei n, const GLuint *textures);
void GL_APIENTRY glDepthFunc (GLenum func);
void GL_APIENTRY glDepthMask (GLboolean flag);
void GL_APIENTRY glDepthRangef (GLfloat n, GLfloat f);
void GL_APIENTRY glDetachShader (GLuint program, GLuint shader);
void GL_APIENTRY glDisable (GLenum cap);
void GL_APIENTRY glDisableVertexAttribArray (GLuint index);
void GL_APIENTRY glDrawArrays (GLenum mode, GLint first, GLsizei count);
void GL_APIENTRY glDrawElements (GLenum mode, GLsizei count, GLenum type, const void *indices);
void GL_APIENTRY glEnable (GLenum cap);
void GL_APIENTRY glEnableVertexAttribArray (GLuint index);
void GL_APIENTRY glFinish (void);
void GL_APIENTRY glFlush (void);
void GL_APIENTRY glFramebufferRenderbuffer (GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
void GL_APIENTRY glFramebufferTexture2D (GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
void GL_APIENTRY glFrontFace (GLenum mode);
void GL_APIENTRY glGenBuffers (GLsizei n, GLuint *buffers);
void GL_APIENTRY glGenerateMipmap (GLenum target);
void GL_APIENTRY glGenFramebuffers (GLsizei n, GLuint *framebuffers);
void GL_APIENTRY glGenRenderbuffers (GLsizei n, GLuint *renderbuffers);
void GL_APIENTRY glGenTextures (GLsizei n, GLuint *textures);
void GL_APIENTRY glGetActiveAttrib (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
void GL_APIENTRY glGetActiveUniform (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLint *size, GLenum *type, GLchar *name);
void GL_APIENTRY glGetAttachedShaders (GLuint program, GLsizei maxCount, GLsizei *count, GLuint *shaders);
GLint GL_APIENTRY glGetAttribLocation (GLuint program, const GLchar *name);
void GL_APIENTRY glGetBooleanv (GLenum pname, GLboolean *data);
void GL_APIENTRY glGetBufferParameteriv (GLenum target, GLenum pname, GLint *params);
GLenum GL_APIENTRY glGetError (void);
void GL_APIENTRY glGetFloatv (GLenum pname, GLfloat *data);
void GL_APIENTRY glGetFramebufferAttachmentParameteriv (GLenum target, GLenum attachment, GLenum pname, GLint *params);
void GL_APIENTRY glGetIntegerv (GLenum pname, GLint *data);
void GL_APIENTRY glGetProgramiv (GLuint program, GLenum pname, GLint *params);
void GL_APIENTRY glGetProgramInfoLog (GLuint program, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void GL_APIENTRY glGetRenderbufferParameteriv (GLenum target, GLenum pname, GLint *params);
void GL_APIENTRY glGetShaderiv (GLuint shader, GLenum pname, GLint *params);
void GL_APIENTRY glGetShaderInfoLog (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void GL_APIENTRY glGetShaderPrecisionFormat (GLenum shadertype, GLenum precisiontype, GLint *range, GLint *precision);
void GL_APIENTRY glGetShaderSource (GLuint shader, GLsizei bufSize, GLsizei *length, GLchar *source);
const GLubyte *GL_APIENTRY glGetString (GLenum name);
void GL_APIENTRY glGetTexParameterfv (GLenum target, GLenum pname, GLfloat *params);
void GL_APIENTRY glGetTexParameteriv (GLenum target, GLenum pname, GLint *params);
void GL_APIENTRY glGetUniformfv (GLuint program, GLint location, GLfloat *params);
void GL_APIENTRY glGetUniformiv (GLuint program, GLint location, GLint *params);
GLint GL_APIENTRY glGetUniformLocation (GLuint program, const GLchar *name);
void GL_APIENTRY glGetVertexAttribfv (GLuint index, GLenum pname, GLfloat *params);
void GL_APIENTRY glGetVertexAttribiv (GLuint index, GLenum pname, GLint *params);
void GL_APIENTRY glGetVertexAttribPointerv (GLuint index, GLenum pname, void **pointer);
void GL_APIENTRY glHint (GLenum target, GLenum mode);
GLboolean GL_APIENTRY glIsBuffer (GLuint buffer);
GLboolean GL_APIENTRY glIsEnabled (GLenum cap);
GLboolean GL_APIENTRY glIsFramebuffer (GLuint framebuffer);
GLboolean GL_APIENTRY glIsProgram (GLuint program);
GLboolean GL_APIENTRY glIsRenderbuffer (GLuint renderbuffer);
GLboolean GL_APIENTRY glIsShader (GLuint shader);
GLboolean GL_APIENTRY glIsTexture (GLuint texture);
void GL_APIENTRY glLineWidth (GLfloat width);
void GL_APIENTRY glLinkProgram (GLuint program);
void GL_APIENTRY glPixelStorei (GLenum pname, GLint param);
void GL_APIENTRY glPolygonOffset (GLfloat factor, GLfloat units);
void GL_APIENTRY glReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels);
void GL_APIENTRY glReleaseShaderCompiler (void);
void GL_APIENTRY glRenderbufferStorage (GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
void GL_APIENTRY glSampleCoverage (GLfloat value, GLboolean invert);
void GL_APIENTRY glScissor (GLint x, GLint y, GLsizei width, GLsizei height);
void GL_APIENTRY glShaderBinary (GLsizei count, const GLuint *shaders, GLenum binaryformat, const void *binary, GLsizei length);
void GL_APIENTRY glShaderSource (GLuint shader, GLsizei count, const GLchar *const*string, const GLint *length);
void GL_APIENTRY glStencilFunc (GLenum func, GLint ref, GLuint mask);
void GL_APIENTRY glStencilFuncSeparate (GLenum face, GLenum func, GLint ref, GLuint mask);
void GL_APIENTRY glStencilMask (GLuint mask);
void GL_APIENTRY glStencilMaskSeparate (GLenum face, GLuint mask);
void GL_APIENTRY glStencilOp (GLenum fail, GLenum zfail, GLenum zpass);
void GL_APIENTRY glStencilOpSeparate (GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
void GL_APIENTRY glTexImage2D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels);
void GL_APIENTRY glTexParameterf (GLenum target, GLenum pname, GLfloat param);
void GL_APIENTRY glTexParameterfv (GLenum target, GLenum pname, const GLfloat *params);
void GL_APIENTRY glTexParameteri (GLenum target, GLenum pname, GLint param);
void GL_APIENTRY glTexParameteriv (GLenum target, GLenum pname, const GLint *params);
void GL_APIENTRY glTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels);
void GL_APIENTRY glUniform1f (GLint location, GLfloat v0);
void GL_APIENTRY glUniform1fv (GLint location, GLsizei count, const GLfloat *value);
void GL_APIENTRY glUniform1i (GLint location, GLint v0);
void GL_APIENTRY glUniform1iv (GLint location, GLsizei count, const GLint *value);
void GL_APIENTRY glUniform2f (GLint location, GLfloat v0, GLfloat v1);
void GL_APIENTRY glUniform2fv (GLint location, GLsizei count, const GLfloat *value);
void GL_APIENTRY glUniform2i (GLint location, GLint v0, GLint v1);
void GL_APIENTRY glUniform2iv (GLint location, GLsizei count, const GLint *value);
void GL_APIENTRY glUniform3f (GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
void GL_APIENTRY glUniform3fv (GLint location, GLsizei count, const GLfloat *value);
void GL_APIENTRY glUniform3i (GLint location, GLint v0, GLint v1, GLint v2);
void GL_APIENTRY glUniform3iv (GLint location, GLsizei count, const GLint *value);
void GL_APIENTRY glUniform4f (GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
void GL_APIENTRY glUniform4fv (GLint location, GLsizei count, const GLfloat *value);
void GL_APIENTRY glUniform4i (GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
void GL_APIENTRY glUniform4iv (GLint location, GLsizei count, const GLint *value);
void GL_APIENTRY glUniformMatrix2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glUniformMatrix3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glUniformMatrix4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glUseProgram (GLuint program);
void GL_APIENTRY glValidateProgram (GLuint program);
void GL_APIENTRY glVertexAttrib1f (GLuint index, GLfloat x);
void GL_APIENTRY glVertexAttrib1fv (GLuint index, const GLfloat *v);
void GL_APIENTRY glVertexAttrib2f (GLuint index, GLfloat x, GLfloat y);
void GL_APIENTRY glVertexAttrib2fv (GLuint index, const GLfloat *v);
void GL_APIENTRY glVertexAttrib3f (GLuint index, GLfloat x, GLfloat y, GLfloat z);
void GL_APIENTRY glVertexAttrib3fv (GLuint index, const GLfloat *v);
void GL_APIENTRY glVertexAttrib4f (GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
void GL_APIENTRY glVertexAttrib4fv (GLuint index, const GLfloat *v);
void GL_APIENTRY glVertexAttribPointer (GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void *pointer);
void GL_APIENTRY glViewport (GLint x, GLint y, GLsizei width, GLsizei height);
typedef unsigned short GLhalf;
void GL_APIENTRY glReadBuffer (GLenum mode);
void GL_APIENTRY glDrawRangeElements (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const void *indices);
void GL_APIENTRY glTexImage3D (GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const void *pixels);
void GL_APIENTRY glTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const void *pixels);
void GL_APIENTRY glCopyTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height);
void GL_APIENTRY glCompressedTexImage3D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const void *data);
void GL_APIENTRY glCompressedTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const void *data);
void GL_APIENTRY glGenQueries (GLsizei n, GLuint *ids);
void GL_APIENTRY glDeleteQueries (GLsizei n, const GLuint *ids);
GLboolean GL_APIENTRY glIsQuery (GLuint id);
void GL_APIENTRY glBeginQuery (GLenum target, GLuint id);
void GL_APIENTRY glEndQuery (GLenum target);
void GL_APIENTRY glGetQueryiv (GLenum target, GLenum pname, GLint *params);
void GL_APIENTRY glGetQueryObjectuiv (GLuint id, GLenum pname, GLuint *params);
GLboolean GL_APIENTRY glUnmapBuffer (GLenum target);
void GL_APIENTRY glGetBufferPointerv (GLenum target, GLenum pname, void **params);
void GL_APIENTRY glDrawBuffers (GLsizei n, const GLenum *bufs);
void GL_APIENTRY glUniformMatrix2x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glUniformMatrix3x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glUniformMatrix2x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glUniformMatrix4x2fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glUniformMatrix3x4fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glUniformMatrix4x3fv (GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glBlitFramebuffer (GLint srcX0, GLint srcY0, GLint srcX1, GLint srcY1, GLint dstX0, GLint dstY0, GLint dstX1, GLint dstY1, GLbitfield mask, GLenum filter);
void GL_APIENTRY glRenderbufferStorageMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height);
void GL_APIENTRY glFramebufferTextureLayer (GLenum target, GLenum attachment, GLuint texture, GLint level, GLint layer);
void *GL_APIENTRY glMapBufferRange (GLenum target, GLintptr offset, GLsizeiptr length, GLbitfield access);
void GL_APIENTRY glFlushMappedBufferRange (GLenum target, GLintptr offset, GLsizeiptr length);
void GL_APIENTRY glBindVertexArray (GLuint array);
void GL_APIENTRY glDeleteVertexArrays (GLsizei n, const GLuint *arrays);
void GL_APIENTRY glGenVertexArrays (GLsizei n, GLuint *arrays);
GLboolean GL_APIENTRY glIsVertexArray (GLuint array);
void GL_APIENTRY glGetIntegeri_v (GLenum target, GLuint index, GLint *data);
void GL_APIENTRY glBeginTransformFeedback (GLenum primitiveMode);
void GL_APIENTRY glEndTransformFeedback (void);
void GL_APIENTRY glBindBufferRange (GLenum target, GLuint index, GLuint buffer, GLintptr offset, GLsizeiptr size);
void GL_APIENTRY glBindBufferBase (GLenum target, GLuint index, GLuint buffer);
void GL_APIENTRY glTransformFeedbackVaryings (GLuint program, GLsizei count, const GLchar *const*varyings, GLenum bufferMode);
void GL_APIENTRY glGetTransformFeedbackVarying (GLuint program, GLuint index, GLsizei bufSize, GLsizei *length, GLsizei *size, GLenum *type, GLchar *name);
void GL_APIENTRY glVertexAttribIPointer (GLuint index, GLint size, GLenum type, GLsizei stride, const void *pointer);
void GL_APIENTRY glGetVertexAttribIiv (GLuint index, GLenum pname, GLint *params);
void GL_APIENTRY glGetVertexAttribIuiv (GLuint index, GLenum pname, GLuint *params);
void GL_APIENTRY glVertexAttribI4i (GLuint index, GLint x, GLint y, GLint z, GLint w);
void GL_APIENTRY glVertexAttribI4ui (GLuint index, GLuint x, GLuint y, GLuint z, GLuint w);
void GL_APIENTRY glVertexAttribI4iv (GLuint index, const GLint *v);
void GL_APIENTRY glVertexAttribI4uiv (GLuint index, const GLuint *v);
void GL_APIENTRY glGetUniformuiv (GLuint program, GLint location, GLuint *params);
GLint GL_APIENTRY glGetFragDataLocation (GLuint program, const GLchar *name);
void GL_APIENTRY glUniform1ui (GLint location, GLuint v0);
void GL_APIENTRY glUniform2ui (GLint location, GLuint v0, GLuint v1);
void GL_APIENTRY glUniform3ui (GLint location, GLuint v0, GLuint v1, GLuint v2);
void GL_APIENTRY glUniform4ui (GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
void GL_APIENTRY glUniform1uiv (GLint location, GLsizei count, const GLuint *value);
void GL_APIENTRY glUniform2uiv (GLint location, GLsizei count, const GLuint *value);
void GL_APIENTRY glUniform3uiv (GLint location, GLsizei count, const GLuint *value);
void GL_APIENTRY glUniform4uiv (GLint location, GLsizei count, const GLuint *value);
void GL_APIENTRY glClearBufferiv (GLenum buffer, GLint drawbuffer, const GLint *value);
void GL_APIENTRY glClearBufferuiv (GLenum buffer, GLint drawbuffer, const GLuint *value);
void GL_APIENTRY glClearBufferfv (GLenum buffer, GLint drawbuffer, const GLfloat *value);
void GL_APIENTRY glClearBufferfi (GLenum buffer, GLint drawbuffer, GLfloat depth, GLint stencil);
const GLubyte *GL_APIENTRY glGetStringi (GLenum name, GLuint index);
void GL_APIENTRY glCopyBufferSubData (GLenum readTarget, GLenum writeTarget, GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
void GL_APIENTRY glGetUniformIndices (GLuint program, GLsizei uniformCount, const GLchar *const*uniformNames, GLuint *uniformIndices);
void GL_APIENTRY glGetActiveUniformsiv (GLuint program, GLsizei uniformCount, const GLuint *uniformIndices, GLenum pname, GLint *params);
GLuint GL_APIENTRY glGetUniformBlockIndex (GLuint program, const GLchar *uniformBlockName);
void GL_APIENTRY glGetActiveUniformBlockiv (GLuint program, GLuint uniformBlockIndex, GLenum pname, GLint *params);
void GL_APIENTRY glGetActiveUniformBlockName (GLuint program, GLuint uniformBlockIndex, GLsizei bufSize, GLsizei *length, GLchar *uniformBlockName);
void GL_APIENTRY glUniformBlockBinding (GLuint program, GLuint uniformBlockIndex, GLuint uniformBlockBinding);
void GL_APIENTRY glDrawArraysInstanced (GLenum mode, GLint first, GLsizei count, GLsizei instancecount);
void GL_APIENTRY glDrawElementsInstanced (GLenum mode, GLsizei count, GLenum type, const void *indices, GLsizei instancecount);
void GL_APIENTRY glGetInteger64v (GLenum pname, GLint64 *data);
void GL_APIENTRY glGetInteger64i_v (GLenum target, GLuint index, GLint64 *data);
void GL_APIENTRY glGetBufferParameteri64v (GLenum target, GLenum pname, GLint64 *params);
void GL_APIENTRY glGenSamplers (GLsizei count, GLuint *samplers);
void GL_APIENTRY glDeleteSamplers (GLsizei count, const GLuint *samplers);
GLboolean GL_APIENTRY glIsSampler (GLuint sampler);
void GL_APIENTRY glBindSampler (GLuint unit, GLuint sampler);
void GL_APIENTRY glSamplerParameteri (GLuint sampler, GLenum pname, GLint param);
void GL_APIENTRY glSamplerParameteriv (GLuint sampler, GLenum pname, const GLint *param);
void GL_APIENTRY glSamplerParameterf (GLuint sampler, GLenum pname, GLfloat param);
void GL_APIENTRY glSamplerParameterfv (GLuint sampler, GLenum pname, const GLfloat *param);
void GL_APIENTRY glGetSamplerParameteriv (GLuint sampler, GLenum pname, GLint *params);
void GL_APIENTRY glGetSamplerParameterfv (GLuint sampler, GLenum pname, GLfloat *params);
void GL_APIENTRY glVertexAttribDivisor (GLuint index, GLuint divisor);
void GL_APIENTRY glBindTransformFeedback (GLenum target, GLuint id);
void GL_APIENTRY glDeleteTransformFeedbacks (GLsizei n, const GLuint *ids);
void GL_APIENTRY glGenTransformFeedbacks (GLsizei n, GLuint *ids);
GLboolean GL_APIENTRY glIsTransformFeedback (GLuint id);
void GL_APIENTRY glPauseTransformFeedback (void);
void GL_APIENTRY glResumeTransformFeedback (void);
void GL_APIENTRY glGetProgramBinary (GLuint program, GLsizei bufSize, GLsizei *length, GLenum *binaryFormat, void *binary);
void GL_APIENTRY glProgramBinary (GLuint program, GLenum binaryFormat, const void *binary, GLsizei length);
void GL_APIENTRY glProgramParameteri (GLuint program, GLenum pname, GLint value);
void GL_APIENTRY glInvalidateFramebuffer (GLenum target, GLsizei numAttachments, const GLenum *attachments);
void GL_APIENTRY glInvalidateSubFramebuffer (GLenum target, GLsizei numAttachments, const GLenum *attachments, GLint x, GLint y, GLsizei width, GLsizei height);
void GL_APIENTRY glTexStorage2D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height);
void GL_APIENTRY glTexStorage3D (GLenum target, GLsizei levels, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth);
void GL_APIENTRY glGetInternalformativ (GLenum target, GLenum internalformat, GLenum pname, GLsizei bufSize, GLint *params);
void GL_APIENTRY glDispatchCompute (GLuint num_groups_x, GLuint num_groups_y, GLuint num_groups_z);
void GL_APIENTRY glDispatchComputeIndirect (GLintptr indirect);
void GL_APIENTRY glDrawArraysIndirect (GLenum mode, const void *indirect);
void GL_APIENTRY glDrawElementsIndirect (GLenum mode, GLenum type, const void *indirect);
void GL_APIENTRY glFramebufferParameteri (GLenum target, GLenum pname, GLint param);
void GL_APIENTRY glGetFramebufferParameteriv (GLenum target, GLenum pname, GLint *params);
void GL_APIENTRY glGetProgramInterfaceiv (GLuint program, GLenum programInterface, GLenum pname, GLint *params);
GLuint GL_APIENTRY glGetProgramResourceIndex (GLuint program, GLenum programInterface, const GLchar *name);
void GL_APIENTRY glGetProgramResourceName (GLuint program, GLenum programInterface, GLuint index, GLsizei bufSize, GLsizei *length, GLchar *name);
void GL_APIENTRY glGetProgramResourceiv (GLuint program, GLenum programInterface, GLuint index, GLsizei propCount, const GLenum *props, GLsizei bufSize, GLsizei *length, GLint *params);
GLint GL_APIENTRY glGetProgramResourceLocation (GLuint program, GLenum programInterface, const GLchar *name);
void GL_APIENTRY glUseProgramStages (GLuint pipeline, GLbitfield stages, GLuint program);
void GL_APIENTRY glActiveShaderProgram (GLuint pipeline, GLuint program);
GLuint GL_APIENTRY glCreateShaderProgramv (GLenum type, GLsizei count, const GLchar *const*strings);
void GL_APIENTRY glBindProgramPipeline (GLuint pipeline);
void GL_APIENTRY glDeleteProgramPipelines (GLsizei n, const GLuint *pipelines);
void GL_APIENTRY glGenProgramPipelines (GLsizei n, GLuint *pipelines);
GLboolean GL_APIENTRY glIsProgramPipeline (GLuint pipeline);
void GL_APIENTRY glGetProgramPipelineiv (GLuint pipeline, GLenum pname, GLint *params);
void GL_APIENTRY glProgramUniform1i (GLuint program, GLint location, GLint v0);
void GL_APIENTRY glProgramUniform2i (GLuint program, GLint location, GLint v0, GLint v1);
void GL_APIENTRY glProgramUniform3i (GLuint program, GLint location, GLint v0, GLint v1, GLint v2);
void GL_APIENTRY glProgramUniform4i (GLuint program, GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
void GL_APIENTRY glProgramUniform1ui (GLuint program, GLint location, GLuint v0);
void GL_APIENTRY glProgramUniform2ui (GLuint program, GLint location, GLuint v0, GLuint v1);
void GL_APIENTRY glProgramUniform3ui (GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2);
void GL_APIENTRY glProgramUniform4ui (GLuint program, GLint location, GLuint v0, GLuint v1, GLuint v2, GLuint v3);
void GL_APIENTRY glProgramUniform1f (GLuint program, GLint location, GLfloat v0);
void GL_APIENTRY glProgramUniform2f (GLuint program, GLint location, GLfloat v0, GLfloat v1);
void GL_APIENTRY glProgramUniform3f (GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
void GL_APIENTRY glProgramUniform4f (GLuint program, GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
void GL_APIENTRY glProgramUniform1iv (GLuint program, GLint location, GLsizei count, const GLint *value);
void GL_APIENTRY glProgramUniform2iv (GLuint program, GLint location, GLsizei count, const GLint *value);
void GL_APIENTRY glProgramUniform3iv (GLuint program, GLint location, GLsizei count, const GLint *value);
void GL_APIENTRY glProgramUniform4iv (GLuint program, GLint location, GLsizei count, const GLint *value);
void GL_APIENTRY glProgramUniform1uiv (GLuint program, GLint location, GLsizei count, const GLuint *value);
void GL_APIENTRY glProgramUniform2uiv (GLuint program, GLint location, GLsizei count, const GLuint *value);
void GL_APIENTRY glProgramUniform3uiv (GLuint program, GLint location, GLsizei count, const GLuint *value);
void GL_APIENTRY glProgramUniform4uiv (GLuint program, GLint location, GLsizei count, const GLuint *value);
void GL_APIENTRY glProgramUniform1fv (GLuint program, GLint location, GLsizei count, const GLfloat *value);
void GL_APIENTRY glProgramUniform2fv (GLuint program, GLint location, GLsizei count, const GLfloat *value);
void GL_APIENTRY glProgramUniform3fv (GLuint program, GLint location, GLsizei count, const GLfloat *value);
void GL_APIENTRY glProgramUniform4fv (GLuint program, GLint location, GLsizei count, const GLfloat *value);
void GL_APIENTRY glProgramUniformMatrix2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glProgramUniformMatrix3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glProgramUniformMatrix4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glProgramUniformMatrix2x3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glProgramUniformMatrix3x2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glProgramUniformMatrix2x4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glProgramUniformMatrix4x2fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glProgramUniformMatrix3x4fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glProgramUniformMatrix4x3fv (GLuint program, GLint location, GLsizei count, GLboolean transpose, const GLfloat *value);
void GL_APIENTRY glValidateProgramPipeline (GLuint pipeline);
void GL_APIENTRY glGetProgramPipelineInfoLog (GLuint pipeline, GLsizei bufSize, GLsizei *length, GLchar *infoLog);
void GL_APIENTRY glBindImageTexture (GLuint unit, GLuint texture, GLint level, GLboolean layered, GLint layer, GLenum access, GLenum format);
void GL_APIENTRY glGetBooleani_v (GLenum target, GLuint index, GLboolean *data);
void GL_APIENTRY glMemoryBarrier (GLbitfield barriers);
void GL_APIENTRY glTexStorage2DMultisample (GLenum target, GLsizei samples, GLenum internalformat, GLsizei width, GLsizei height, GLboolean fixedsamplelocations);
void GL_APIENTRY glGetMultisamplefv (GLenum pname, GLuint index, GLfloat *val);
void GL_APIENTRY glSampleMaski (GLuint maskNumber, GLbitfield mask);
void GL_APIENTRY glGetTexLevelParameteriv (GLenum target, GLint level, GLenum pname, GLint *params);
void GL_APIENTRY glGetTexLevelParameterfv (GLenum target, GLint level, GLenum pname, GLfloat *params);
void GL_APIENTRY glBindVertexBuffer (GLuint bindingindex, GLuint buffer, GLintptr offset, GLsizei stride);
void GL_APIENTRY glVertexAttribFormat (GLuint attribindex, GLint size, GLenum type, GLboolean normalized, GLuint relativeoffset);
void GL_APIENTRY glVertexAttribIFormat (GLuint attribindex, GLint size, GLenum type, GLuint relativeoffset);
void GL_APIENTRY glVertexAttribBinding (GLuint attribindex, GLuint bindingindex);
void GL_APIENTRY glVertexBindingDivisor (GLuint bindingindex, GLuint divisor);